# Generated by Django 5.2 on 2025-05-01 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classe de compte',
                'verbose_name_plural': 'Classes de comptes',
                'ordering': ['number'],
                'unique_together': {('tenant_id', 'number')},
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.accountclass')),
            ],
            options={
                'verbose_name': 'Catégorie de compte',
                'verbose_name_plural': 'Catégories de comptes',
                'ordering': ['code'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Code unique pour l'exercice (ex: FY2023)", max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Empêche toute modification des transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercice fiscal',
                'verbose_name_plural': 'Exercices fiscaux',
                'ordering': ['-start_date'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Niveau hiérarchique du compte')),
                ('type', models.CharField(choices=[('ASSET', 'Actif'), ('LIABILITY', 'Passif'), ('EQUITY', 'Capitaux propres'), ('REVENUE', 'Produit'), ('EXPENSE', 'Charge')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reconcilable', models.BooleanField(default=True, help_text='Indique si le compte peut être rapproché')),
                ('is_tax_relevant', models.BooleanField(default=False, help_text='Indique si le compte est pertinent pour la TVA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.accountcategory')),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.accountclass')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['code'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number', models.PositiveSmallIntegerField(help_text="Numéro de la période dans l'exercice")),
                ('is_closed', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.fiscalyear')),
            ],
            options={
                'verbose_name': 'Période fiscale',
                'verbose_name_plural': 'Périodes fiscales',
                'ordering': ['fiscal_year', 'number'],
                'unique_together': {('fiscal_year', 'number')},
            },
        ),
    ]
