# Generated by Django 5.2 on 2025-05-01 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code unique du tiers', max_length=20)),
                ('name', models.CharField(help_text='Nom ou raison sociale du tiers', max_length=200)),
                ('type', models.CharField(choices=[('CUSTOMER', 'Client'), ('SUPPLIER', 'Fournisseur'), ('EMPLOYEE', 'Employé'), ('OTHER', 'Autre')], max_length=20)),
                ('address', models.TextField(blank=True, help_text='Adresse complète', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Notes et informations additionnelles', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Compte comptable associé au tiers', on_delete=django.db.models.deletion.PROTECT, related_name='tiers', to='core.account')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['code', 'name'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
    ]
