# Generated by Django 5.2 on 2025-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='code',
            field=models.CharField(help_text="Code unique du tiers (sera formaté en majuscules et complété jusqu'à 6 caractères)", max_length=20),
        ),
    ]
